// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/yyewolf/ssarchiver/internal/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPlayerAlias(db *gorm.DB, opts ...gen.DOOption) playerAlias {
	_playerAlias := playerAlias{}

	_playerAlias.playerAliasDo.UseDB(db, opts...)
	_playerAlias.playerAliasDo.UseModel(&model.PlayerAlias{})

	tableName := _playerAlias.playerAliasDo.TableName()
	_playerAlias.ALL = field.NewAsterisk(tableName)
	_playerAlias.OldID = field.NewString(tableName, "old_id")
	_playerAlias.PlayerID = field.NewString(tableName, "player_id")
	_playerAlias.Player = playerAliasBelongsToPlayer{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Player", "model.Player"),
	}

	_playerAlias.fillFieldMap()

	return _playerAlias
}

type playerAlias struct {
	playerAliasDo playerAliasDo

	ALL      field.Asterisk
	OldID    field.String
	PlayerID field.String
	Player   playerAliasBelongsToPlayer

	fieldMap map[string]field.Expr
}

func (p playerAlias) Table(newTableName string) *playerAlias {
	p.playerAliasDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p playerAlias) As(alias string) *playerAlias {
	p.playerAliasDo.DO = *(p.playerAliasDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *playerAlias) updateTableName(table string) *playerAlias {
	p.ALL = field.NewAsterisk(table)
	p.OldID = field.NewString(table, "old_id")
	p.PlayerID = field.NewString(table, "player_id")

	p.fillFieldMap()

	return p
}

func (p *playerAlias) WithContext(ctx context.Context) IPlayerAliasDo {
	return p.playerAliasDo.WithContext(ctx)
}

func (p playerAlias) TableName() string { return p.playerAliasDo.TableName() }

func (p playerAlias) Alias() string { return p.playerAliasDo.Alias() }

func (p playerAlias) Columns(cols ...field.Expr) gen.Columns { return p.playerAliasDo.Columns(cols...) }

func (p *playerAlias) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *playerAlias) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["old_id"] = p.OldID
	p.fieldMap["player_id"] = p.PlayerID

}

func (p playerAlias) clone(db *gorm.DB) playerAlias {
	p.playerAliasDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Player.db = db.Session(&gorm.Session{Initialized: true})
	p.Player.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p playerAlias) replaceDB(db *gorm.DB) playerAlias {
	p.playerAliasDo.ReplaceDB(db)
	p.Player.db = db.Session(&gorm.Session{})
	return p
}

type playerAliasBelongsToPlayer struct {
	db *gorm.DB

	field.RelationField
}

func (a playerAliasBelongsToPlayer) Where(conds ...field.Expr) *playerAliasBelongsToPlayer {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a playerAliasBelongsToPlayer) WithContext(ctx context.Context) *playerAliasBelongsToPlayer {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a playerAliasBelongsToPlayer) Session(session *gorm.Session) *playerAliasBelongsToPlayer {
	a.db = a.db.Session(session)
	return &a
}

func (a playerAliasBelongsToPlayer) Model(m *model.PlayerAlias) *playerAliasBelongsToPlayerTx {
	return &playerAliasBelongsToPlayerTx{a.db.Model(m).Association(a.Name())}
}

func (a playerAliasBelongsToPlayer) Unscoped() *playerAliasBelongsToPlayer {
	a.db = a.db.Unscoped()
	return &a
}

type playerAliasBelongsToPlayerTx struct{ tx *gorm.Association }

func (a playerAliasBelongsToPlayerTx) Find() (result *model.Player, err error) {
	return result, a.tx.Find(&result)
}

func (a playerAliasBelongsToPlayerTx) Append(values ...*model.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a playerAliasBelongsToPlayerTx) Replace(values ...*model.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a playerAliasBelongsToPlayerTx) Delete(values ...*model.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a playerAliasBelongsToPlayerTx) Clear() error {
	return a.tx.Clear()
}

func (a playerAliasBelongsToPlayerTx) Count() int64 {
	return a.tx.Count()
}

func (a playerAliasBelongsToPlayerTx) Unscoped() *playerAliasBelongsToPlayerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type playerAliasDo struct{ gen.DO }

type IPlayerAliasDo interface {
	gen.SubQuery
	Debug() IPlayerAliasDo
	WithContext(ctx context.Context) IPlayerAliasDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlayerAliasDo
	WriteDB() IPlayerAliasDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlayerAliasDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlayerAliasDo
	Not(conds ...gen.Condition) IPlayerAliasDo
	Or(conds ...gen.Condition) IPlayerAliasDo
	Select(conds ...field.Expr) IPlayerAliasDo
	Where(conds ...gen.Condition) IPlayerAliasDo
	Order(conds ...field.Expr) IPlayerAliasDo
	Distinct(cols ...field.Expr) IPlayerAliasDo
	Omit(cols ...field.Expr) IPlayerAliasDo
	Join(table schema.Tabler, on ...field.Expr) IPlayerAliasDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlayerAliasDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlayerAliasDo
	Group(cols ...field.Expr) IPlayerAliasDo
	Having(conds ...gen.Condition) IPlayerAliasDo
	Limit(limit int) IPlayerAliasDo
	Offset(offset int) IPlayerAliasDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayerAliasDo
	Unscoped() IPlayerAliasDo
	Create(values ...*model.PlayerAlias) error
	CreateInBatches(values []*model.PlayerAlias, batchSize int) error
	Save(values ...*model.PlayerAlias) error
	First() (*model.PlayerAlias, error)
	Take() (*model.PlayerAlias, error)
	Last() (*model.PlayerAlias, error)
	Find() ([]*model.PlayerAlias, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlayerAlias, err error)
	FindInBatches(result *[]*model.PlayerAlias, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PlayerAlias) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlayerAliasDo
	Assign(attrs ...field.AssignExpr) IPlayerAliasDo
	Joins(fields ...field.RelationField) IPlayerAliasDo
	Preload(fields ...field.RelationField) IPlayerAliasDo
	FirstOrInit() (*model.PlayerAlias, error)
	FirstOrCreate() (*model.PlayerAlias, error)
	FindByPage(offset int, limit int) (result []*model.PlayerAlias, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlayerAliasDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p playerAliasDo) Debug() IPlayerAliasDo {
	return p.withDO(p.DO.Debug())
}

func (p playerAliasDo) WithContext(ctx context.Context) IPlayerAliasDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playerAliasDo) ReadDB() IPlayerAliasDo {
	return p.Clauses(dbresolver.Read)
}

func (p playerAliasDo) WriteDB() IPlayerAliasDo {
	return p.Clauses(dbresolver.Write)
}

func (p playerAliasDo) Session(config *gorm.Session) IPlayerAliasDo {
	return p.withDO(p.DO.Session(config))
}

func (p playerAliasDo) Clauses(conds ...clause.Expression) IPlayerAliasDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playerAliasDo) Returning(value interface{}, columns ...string) IPlayerAliasDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playerAliasDo) Not(conds ...gen.Condition) IPlayerAliasDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playerAliasDo) Or(conds ...gen.Condition) IPlayerAliasDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playerAliasDo) Select(conds ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playerAliasDo) Where(conds ...gen.Condition) IPlayerAliasDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playerAliasDo) Order(conds ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playerAliasDo) Distinct(cols ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playerAliasDo) Omit(cols ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playerAliasDo) Join(table schema.Tabler, on ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playerAliasDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playerAliasDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playerAliasDo) Group(cols ...field.Expr) IPlayerAliasDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playerAliasDo) Having(conds ...gen.Condition) IPlayerAliasDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playerAliasDo) Limit(limit int) IPlayerAliasDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playerAliasDo) Offset(offset int) IPlayerAliasDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playerAliasDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayerAliasDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playerAliasDo) Unscoped() IPlayerAliasDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playerAliasDo) Create(values ...*model.PlayerAlias) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playerAliasDo) CreateInBatches(values []*model.PlayerAlias, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playerAliasDo) Save(values ...*model.PlayerAlias) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playerAliasDo) First() (*model.PlayerAlias, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerAlias), nil
	}
}

func (p playerAliasDo) Take() (*model.PlayerAlias, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerAlias), nil
	}
}

func (p playerAliasDo) Last() (*model.PlayerAlias, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerAlias), nil
	}
}

func (p playerAliasDo) Find() ([]*model.PlayerAlias, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlayerAlias), err
}

func (p playerAliasDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlayerAlias, err error) {
	buf := make([]*model.PlayerAlias, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playerAliasDo) FindInBatches(result *[]*model.PlayerAlias, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playerAliasDo) Attrs(attrs ...field.AssignExpr) IPlayerAliasDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playerAliasDo) Assign(attrs ...field.AssignExpr) IPlayerAliasDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playerAliasDo) Joins(fields ...field.RelationField) IPlayerAliasDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playerAliasDo) Preload(fields ...field.RelationField) IPlayerAliasDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playerAliasDo) FirstOrInit() (*model.PlayerAlias, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerAlias), nil
	}
}

func (p playerAliasDo) FirstOrCreate() (*model.PlayerAlias, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlayerAlias), nil
	}
}

func (p playerAliasDo) FindByPage(offset int, limit int) (result []*model.PlayerAlias, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playerAliasDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playerAliasDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playerAliasDo) Delete(models ...*model.PlayerAlias) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playerAliasDo) withDO(do gen.Dao) *playerAliasDo {
	p.DO = *do.(*gen.DO)
	return p
}
